bookmarks/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('details/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('new/', views.CreateView.as_view(), name='create'),
]

punaise/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('bookmarks/', include('bookmarks.urls')),
    path('admin/', admin.site.urls),
]

bookmarks/models.py
from django.db import models


class Bookmark(models.Model):
    title = models.CharField(max_length=400, blank=True)
    url = models.URLField(max_length=400)
    description = models.CharField(max_length=1000, blank=True)
    created_at = models.DateTimeField('creation date', auto_now_add=True)

    def __str__(self):
        return self.url

'''
class MediaObject(models.Model):
    bookmark = models.ForeignKey(Bookmark, on_delete=models.CASCADE)

class Tag(models.Model):
'''

bookmarks/forms.py
from django import forms

class NewBookmarkForm(forms.Form):
    url = forms.URLField()

bookmarks/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Bookmark
from .forms import NewBookmarkForm


class IndexView(generic.ListView):
    template_name = 'bookmarks/index.html'

    def get_queryset(self):
        """Return the last five published bookmarks."""
        return Bookmark.objects.order_by('-created_at')[:5]

class DetailView(generic.DetailView):
    model = Bookmark
    template_name = 'bookmarks/detail.html'

class CreateView(generic.edit.CreateView):
    model = Bookmark
    template_name = 'bookmarks/new.html'
    fields = ['url']
    success_url = '/'

    def form_valid(self, form):
        # form.send_email()
        return super().form_valid(form)

bookmarks/templates/bookmarks/detail.html
<dl>
  <dt>Title</dt>
  <dd>{{ bookmark.title }}</dd>
  <dt>URL</dt>
  <dd><a href="{{ bookmark.url }}" target="_blank">{{ bookmark.url }}</a></dd>
  <dt>Created at</dt>
  <dd>{{ bookmark.created_at }}</dd>
</dl>

bookmarks/templates/bookmarks/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'bookmarks/style.css' %}">

{% if bookmark_list %}
    <ul>
    {% for bookmark in bookmark_list %}
        <li><a href="{% url 'detail' bookmark.id %}">
          {% if bookmark.title %}
            {{ bookmark.title }}
          {% else %}
            {{ bookmark.url }}
          {% endif %}
        </a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No saved bookmarks.</p>
{% endif %}

<ul>
  <li><a href="{% url 'index' %}">Home</a></li>
  <li><a href="{% url 'create' %}">Add new</a></li>
</ul>

bookmarks/templates/bookmarks/new.html
<h1>New bookmark</h1>

<form action="{% url 'create' %}" method="post">
{% csrf_token %}
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <input name="url" id="url">
  <label for="url">URL</label><br>

<input type="submit" value="Save">
</form>